[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  publish = "."
  port = 8888
  targetPort = 8080
  autoLaunch = false

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
